cmake_minimum_required(VERSION 3.22)
project(synesthesia_tokenizer LANGUAGES C CXX)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_POSITION_INDEPENDENT_CODE ON)
set(SPM_ENABLE_SHARED OFF CACHE BOOL "" FORCE)
set(SPM_BUILD_TEST OFF CACHE BOOL "" FORCE)
set(SPM_ENABLE_TCMALLOC OFF CACHE BOOL "" FORCE)
set(SPM_ENABLE_NFKC_COMPILE OFF CACHE BOOL "" FORCE)
add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/../build/dependencies/sentencepiece-0.2.1 sentencepiece EXCLUDE_FROM_ALL)
add_library(name_tokenizer SHARED name_tokenizer.cpp)
target_include_directories(name_tokenizer PRIVATE ../build/dependencies/sentencepiece-0.2.1/src)
target_link_libraries(name_tokenizer sentencepiece-static log)
